/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/devices.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.dino.geometry}
        material={materials.dino}
        position={[0.77, -1.354, 3.367]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[2.863, 1.583, 1.68]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Body036.geometry}
        material={materials.Purple}
        position={[0.587, -1.254, 0.917]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-0.268, -1.118, -0.847]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Switch_border001.geometry}
        material={materials['Device - PurpleYellow']}
        position={[0.81, -1.267, 0.917]}
        scale={[0.091, 0.241, 0.122]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Switch001.geometry}
        material={materials.Yellow}
        position={[0.712, -1.339, 0.917]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.222, 0.067, 0.251]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Screw001.geometry}
        material={materials.Yellow}
        position={[0.871, -0.638, 0.917]}
        scale={0.072}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube006.geometry}
          material={nodes.Cube006.material}
          position={[0.531, 0.002, 0]}
          scale={[0.614, 1.287, 0.167]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Screw_2001.geometry}
        material={materials.Yellow}
        position={[0.871, -1.861, 0.917]}
        scale={0.072}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube015.geometry}
          material={nodes.Cube015.material}
          position={[0.531, 0.002, 0]}
          scale={[0.614, 1.287, 0.167]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Body008.geometry}
        material={materials['Device - PurpleYellow']}
        position={[0, 5.221, 0.99]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-0.434, -0.587, -0.583]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Rod_square.geometry}
        material={materials['Device - PurpleYellow']}
        position={[0.43, 5.221, 0.99]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-0.099, -0.363, -0.36]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Rod_base.geometry}
        material={materials['Device - PurpleYellow']}
        position={[0.608, 5.214, 0.972]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.176}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Rod_stick.geometry}
        material={materials['Device - PurpleYellow']}
        position={[1.051, 5.214, 0.972]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.075, 0.226, 0.075]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ball.geometry}
        material={materials['Device - PurpleYellow']}
        position={[1.483, 5.216, 0.961]}
        scale={0.221}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Body003.geometry}
        material={materials['Device - PurpleYellow']}
        position={[0.277, 5.314, 1.478]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-0.213, -0.049, -0.172]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Body004.geometry}
        material={materials['Device - PurpleYellow']}
        position={[0.44, 5.795, 0.413]}
        scale={0.069}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Body005.geometry}
        material={materials['Device - PurpleYellow']}
        position={[0.277, 5.314, 0.476]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-0.213, -0.049, -0.172]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Body006.geometry}
        material={materials['Device - PurpleYellow']}
        position={[0.44, 4.627, 1.569]}
        rotation={[-Math.PI, 0, 0]}
        scale={0.069}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder003.geometry}
        material={materials['Purple.005']}
        position={[0, 5.544, 1.605]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.134, 0.04, 0.134]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005.geometry}
        material={materials.Yellow}
        position={[0, 5.796, 3.127]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-0.095, -0.028, -0.095]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube016.geometry}
        material={materials.Yellow}
        position={[0, 5.796, 3.628]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-0.095, -0.028, -0.279]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Body020.geometry}
        material={materials.Purple}
        position={[0, 2.18, 4.447]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-0.323, -1.347, -1.021]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Outlet_in004.geometry}
        material={materials.Yellow}
        position={[0.073, 1.594, 4.447]}
        scale={0.326}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Body030.geometry}
          material={materials['Purple.004']}
          position={[0.789, -0.45, 0.029]}
          scale={[0.475, 0.137, 0.124]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Body031.geometry}
          material={materials['Purple.004']}
          position={[0.72, 0.222, 0.417]}
          scale={[0.355, 0.267, 0.092]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Body032.geometry}
          material={materials['Purple.004']}
          position={[0.789, 0.189, -0.368]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[-0.355, -0.228, -0.092]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Outlet_in005.geometry}
        material={materials.Yellow}
        position={[0.073, 2.773, 4.447]}
        scale={0.326}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Body033.geometry}
          material={materials['Purple.001']}
          position={[0.789, 0.189, -0.368]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[-0.355, -0.228, -0.092]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Body034.geometry}
          material={materials['Purple.001']}
          position={[0.72, 0.222, 0.417]}
          scale={[0.355, 0.267, 0.092]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Body035.geometry}
          material={materials['Purple.001']}
          position={[0.789, -0.45, 0.029]}
          scale={[0.475, 0.137, 0.124]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube012.geometry}
        material={materials.Purple}
        position={[0.446, 2.858, 4.447]}
        rotation={[0, 0, -Math.PI]}
        scale={[0.032, 0.2, 0.264]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube013.geometry}
        material={materials.Purple}
        position={[0.639, 2.858, 4.447]}
        rotation={[0, 0, -Math.PI]}
        scale={[0.207, 0.134, 0.177]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube014.geometry}
        material={materials.Purple}
        position={[0.946, 2.858, 4.447]}
        rotation={[0, 0, -Math.PI]}
        scale={[0.132, 0.076, 0.114]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Body018.geometry}
        material={materials['Device - PurpleYellow']}
        position={[0, 5.271, 4.105]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-0.434, -0.525, -1.371]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text.geometry}
        material={materials.Purple}
        position={[0.367, 4.969, 5.285]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.805, 0.88, 0.88]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder001.geometry}
        material={materials.Purple}
        position={[0, 4.717, 4.807]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.134, 0.04, 0.134]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Body019.geometry}
        material={materials['Device - PurpleYellow']}
        position={[0, 3.199, 1.108]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-0.434, -0.525, -1.1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003.geometry}
        material={materials['Device - PurpleYellow']}
        position={[0.38, 3.199, 1.108]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-0.339, -0.411, -1.023]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cable_port001.geometry}
        material={materials.Purple}
        position={[0, 3.736, 1.862]}
        rotation={[-Math.PI, 0, 0]}
        scale={[0.134, 0.04, 0.134]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials.Yellow}
        position={[0, 3.587, 0.807]}
        scale={[0.216, 0.187, 0.047]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Body040.geometry}
        material={materials['Dark Indigo']}
        position={[0.124, 2.353, 1.108]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-0.369, -0.297, -0.972]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cable_port.geometry}
        material={materials.Purple}
        position={[0, 1.301, 2.265]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.134, 0.04, 0.134]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Body.geometry}
        material={materials['Device - PurpleYellow']}
        position={[0, -1.334, 2.279]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-0.561, -1.436, -2.474]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Side_piece.geometry}
        material={materials['Device - PurpleYellow']}
        position={[0, -1.334, 5.169]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-0.342, -0.875, -0.319]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Screen_base.geometry}
        material={materials['Device - PurpleYellow']}
        position={[0.38, -1.334, 3.247]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-0.342, -1.093, -1.335]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Screen.geometry}
        material={materials['Dark Indigo']}
        position={[0.727, -1.334, 3.247]}
        rotation={[0, 0, -Math.PI]}
        scale={[0.027, 0.881, 1.077]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cable_port002.geometry}
        material={materials['Purple.006']}
        position={[0, 0.218, 4.735]}
        rotation={[-Math.PI, 0, 0]}
        scale={[0.134, 0.04, 0.134]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Top_piece.geometry}
        material={materials['Device - PurpleYellow']}
        position={[0.019, 0.134, 3.937]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-0.654, -0.063, -0.955]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NurbsPath.geometry}
        material={materials['Cable Indigo']}
        position={[0, 4.047, 3.422]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NurbsPath001.geometry}
        material={materials['Cable Indigo']}
        position={[0, 4.047, 2.803]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.919, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NurbsPath002.geometry}
        material={materials['Cable Indigo']}
        position={[0, 4.145, 2.455]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NurbsPath003.geometry}
        material={materials['Cable Indigo']}
        position={[0, 2.144, 2.974]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NurbsPath004.geometry}
        material={materials['Cable Indigo']}
        position={[0, 0.524, 2.877]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NurbsPath005.geometry}
        material={materials['Cable Indigo']}
        position={[0, 0.524, 3.36]}
        rotation={[0, Math.PI / 2, 0]}
      />
    </group>
  )
}

useGLTF.preload('/devices.gltf')